groups:
- name: supplychain-finance-alerts
  rules:
  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "高错误率"
      description: "HTTP 5xx错误率超过5%"

  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "服务宕机"
      description: "服务 {{ $labels.job }} 已宕机"

  - alert: HighMemoryUsage
    expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "高内存使用率"
      description: "容器内存使用率超过80%"

  - alert: HighCPUUsage
    expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "高CPU使用率"
      description: "容器CPU使用率超过80%"

  - alert: DiskSpaceLow
    expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "磁盘空间不足"
      description: "磁盘可用空间不足10%"

  - alert: DatabaseConnectionError
    expr: rate(database_connection_errors_total[5m]) > 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "数据库连接错误"
      description: "数据库连接出现错误"

  - alert: MPCThresholdBreached
    expr: mpc_threshold_breached_total > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "MPC门限被突破"
      description: "MPC安全门限被突破，可能存在安全风险"